parameters:
    # params

services:
    smart_information_systems_sms.transport.configuration_container:
        class: SmartInformationSystems\SmsBundle\Transport\ConfigurationContainer

    sis_sms:
        class: SmartInformationSystems\SmsBundle\Service\Sms
        arguments:
            - "@smart_information_systems_sms.transport.configuration_container"
            - "@service_container"
            - "@templating"
